server:
  # service startup port
  port: :

redis:
  uri: redis:6379
  user:
  password:
  db: 0

nats:
  uri: 

network:
  - id: 314159
    name: FileCoin-Calibration
    idPrefix: t0
    queryRpc:
      - 
    contractRpc: 
    oracleContract: 
    oracleStartHeight: 
    oracleAbi: oracle.json

github:
  # github token
  token:
    - 
    # graphql api
  graphql: https://api.github.com/graphql
