name: Power-snapshot-test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'power-snapshot/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'power-snapshot/*'

jobs:
  snapshot-test:
    runs-on: ubuntu-latest

    services:
      reids:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: |
          cd ./power-snapshot
          go mod tidy   

      - name: Copy config file to test dir
        run: |
          cd ./power-snapshot
          cp ./abi/* ./internal/service
          cp ./abi/* ./utils


      - name: Test
        run: |
          cd ./power-snapshot
          go test -v ./utils/lotus_rpc_test.go
          go test -v ./service/power_test.go
          go test -v ./service/developer_test.go
